import { Giftcards } from '../../interfaces/payment-flex/giftcards.interface';

export const giftcards: Giftcards[] = [
	{
		id: 1,
    is_Type: 'Giftcards',
		is_top_5: 'Yes',
		retail: 'Prezzee',
		slug: 'prezzee',
		image: 'assets/top-discounts/giftcard-00.jpg',
		website: 'https://www.prezzee.uk/',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		choosing_type: 'Someone else',
		gift_values: [10, 20, 30, 40, 50],
		quantity: [1, 2, 3, 4, 5],
		availability: 'Both',
		valid_to: new Date('2026-09-09'),
		date: new Date('2026-09-09')
	},
	{
		id: 2,
		is_top_5: 'Yes',
		retail: 'Love2Shop',
		slug: 'love2shop',
		image: 'assets/top-discounts/giftcard-01.jpg',
		website: 'https://www.prezzee.uk/',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		choosing_type: 'Someone else',
		gift_values: [10, 20, 30, 40, 50],
		quantity: [1, 2, 3, 4, 5],
		availability: 'Both',
		valid_to: new Date('2026-09-09'),
		date: new Date('2026-09-09')
	},
	{
		id: 3,
		is_top_5: 'Yes',
		retail: 'Asos',
		slug: 'asos',
		image: 'assets/top-discounts/giftcard-02.jpg',
		website: 'https://www.prezzee.uk/',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		choosing_type: 'Someone else',
		gift_values: [10, 20, 30, 40, 50],
		quantity: [1, 2, 3, 4, 5],
		availability: 'Both',
		valid_to: new Date('2026-09-09'),
		date: new Date('2026-09-09')
	},
	{
		id: 4,
		is_top_5: 'No',
		retail: 'River Island',
		slug: 'riverIsland',
		image: 'assets/top-discounts/giftcard-03.jpg',
		website: 'https://www.prezzee.uk/',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		choosing_type: 'Someone else',
		gift_values: [10, 20, 30, 40, 50],
		quantity: [1, 2, 3, 4, 5],
		availability: 'Both',
		valid_to: new Date('2026-09-09'),
		date: new Date('2026-09-09')
	},
	{
		id: 5,
		is_top_5: 'No',
		retail: 'IKEA',
		slug: 'ikea',
		image: 'assets/top-discounts/giftcard-04.jpg',
		website: 'https://www.prezzee.uk/',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		choosing_type: 'Someone else',
		gift_values: [10, 20, 30, 40, 50],
		quantity: [1, 2, 3, 4, 5],
		availability: 'Both',
		valid_to: new Date('2026-09-09'),
		date: new Date('2026-09-09')
	},
]
